name: cozy 
base: core22 
adopt-info: cozy
grade: stable 
confinement: strict 

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  cozy-mpris:
    interface: mpris
    name: Cozy
  cozy:
    interface: dbus
    bus: session
    name: com.github.geigi.cozy

parts:
  cozy:
    plugin: meson
    source: https://github.com/geigi/cozy.git
    source-tag: '1.3.0'
    source-depth: 1
    meson-parameters:
      - --prefix=/snap/cozy/current/usr
    build-packages:
      - libgranite-dev
    stage-packages:
      - python3-gst-1.0
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/cozy/current/usr/bin/com.github.geigi.cozy"
    organize:
      snap/cozy/current/usr: usr
    parse-info: [ usr/share/metainfo/com.github.geigi.cozy.appdata.xml ]

  python-deps:
    after:
      - cozy
    source: .
    plugin: python
    python-packages:
      - distro==1.9.0
      - mutagen==1.47.0
      - peewee==3.17.1
      - pytz==2024.1
      - requests==2.31.0
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    prime:
      - -snap
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -usr/bin/wheel
      - -usr/lib/python3.10/dist-packages/pip*
      - -usr/lib/python3.10/dist-packages/pkg_resources
      - -usr/lib/python3.10/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages

plugs:
  shared-memory:
    private: true

apps:
  cozy:
    command: usr/bin/com.github.geigi.cozy
    common-id: com.github.geigi.cozy
    desktop: usr/share/applications/com.github.geigi.cozy.desktop
    extensions: [ gnome ]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GDK_DEBUG: 'portals'
    plugs:
      - audio-playback
      - home
      - shared-memory
      - removable-media
      - mount-observe
    slots:
      - cozy-mpris
