name: cozy # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.2.1' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: cozy
icon: com.github.geigi.cozy.svg

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

slots:
  cozy-mpris:
    interface: mpris
    name: Cozy
  cozy:
    interface: dbus
    bus: session
    name: com.github.geigi.cozy
parts:
  cozy:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/geigi/cozy.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    meson-parameters:
      - --prefix=/snap/cozy/current/usr
    build-packages:
      - libgranite-dev
    stage-packages:
      - python3-gst-1.0
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/patches/meson.patch
      pip install --target=$CRAFT_PART_INSTALL/snap/cozy/current/usr/lib/python3/dist-packages requests==2.28.1
      pip install --target=$CRAFT_PART_INSTALL/snap/cozy/current/usr/lib/python3/dist-packages distro==1.7.0
      pip install --target=$CRAFT_PART_INSTALL/snap/cozy/current/usr/lib/python3/dist-packages mutagen==1.45.1
      pip install --target=$CRAFT_PART_INSTALL/snap/cozy/current/usr/lib/python3/dist-packages packaging==21.3
      pip install --target=$CRAFT_PART_INSTALL/snap/cozy/current/usr/lib/python3/dist-packages peewee==3.15.2
      pip install --target=$CRAFT_PART_INSTALL/snap/cozy/current/usr/lib/python3/dist-packages pytz==2022.1
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/cozy/current/usr/bin/com.github.geigi.cozy"
    organize:
      snap/cozy/current/usr: usr
    parse-info: [ usr/share/metainfo/com.github.geigi.cozy.appdata.xml ]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - cozy
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gtk-common-themes
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
plugs:
  # required to use multiprocessing semaphores
  shared-memory:
    private: true
apps:
  cozy:
    command: usr/bin/com.github.geigi.cozy
    common-id: com.github.geigi.cozy
    desktop: usr/share/applications/com.github.geigi.cozy.desktop
    extensions: [ gnome ]
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
    plugs:
      - home
      - shared-memory
      - removable-media
    slots:
      - cozy-mpris
